### ISSUE TITLE
Thermal broadening?

### ISSUE THREAD

**Issue by domeckert** [jeremysanders/lognorm#1]
Hi Jeremy,

Thanks very much for this code, this is super useful

I have a question regarding the implementation of lognorm. Are you including thermal broadening in the model? I made some simulations in the context of XRISM to check how the line ratios depend on the temperature distribution, and I found that the lines produced by lognorm appear somewhat broader than the lines of the single APEC model. You can see an example below, where I show a zoom-in on the Fe XXV complex simulated with lognorm (data points) and refitted with a single APEC. As you can see, there are strong residuals in the wings, showing that the lines are broader. In the case of a multi-temperature structure I would have expected the line ratios to change, but not the line width

Thanks for your help
Dominique

[lognorm.pdf](https://github.com/jeremysanders/lognorm/files/14177598/lognorm.pdf)

**Comment by jeremysanders** [comment]
Hi Dominique - yes, I think I switched on the thermal broadening when calling the APEC code. I think it's this line:

https://github.com/jeremysanders/lognorm/blob/10a0e65f0198bdbed9fab5e03ab35b24ea649ac4/clclognorm.cxx#L110C1-L110C22

If you change 1 to 0 and recompile, this should switch it off. Alternatively, using "xset APECTHERMAL yes" should enable it for APEC for comparison.

Cheers

Jeremy

**Comment by domeckert** [comment]
Thanks for the quick response and for confirming what I suspected. I'll try again by switching on thermal broadening in APEC.

Cheers
Dominique
